import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Car rental | Головна",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <>
      <main className={`antialiased min-h-screen`}>{children}</main>
    </>
  );
}
